name: build and deploy

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    pages: write      # to deploy to Pages
    id-token: write

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Install Python dependencies
        run: |
            python3 -m pip install -r requirements.txt

      - name: Build web
        run: |
            python3 main.py
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        